services:
  nsite:
    build: .
    image: ghcr.io/hzrd149/nsite-gateway:master
    restart: unless-stopped
    environment:
      LOOKUP_RELAYS: wss://user.kindpag.es,wss://purplepag.es
      CACHE_PATH: /cache/nsite-gateway.kv
      BLOSSOM_PROXY: http://blossom-cache:24242
    volumes:
      - nsite-cache:/cache

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nsite

  blossom-cache:
    image: ghcr.io/hzrd149/flower-cache:latest
    restart: unless-stopped
    volumes:
      - blossom-cache:/cache

volumes:
  nsite-cache:
  caddy_data:
  caddy_config:
  blossom-cache:
