services:
  nsite:
    build: .
    image: ghcr.io/hzrd149/nsite-gateway:master
    restart: unless-stopped
    environment:
      LOOKUP_RELAYS: wss://user.kindpag.es,wss://purplepag.es
      NOSTR_RELAYS: wss://relay.damus.io,wss://nos.lol,wss://nsite.run,wss://relay.primal.net
      CACHE_PATH: /cache/nsite-gateway.kv
      BLOSSOM_PROXY: http://blossom:24242
    volumes:
      - nsite_cache:/cache
    ports:
      - 3000:3000

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nsite

  blossom:
    image: ghcr.io/hzrd149/flower-cache:latest
    restart: unless-stopped
    volumes:
      - blossom_cache:/cache

volumes:
  nsite_cache:
  caddy_data:
  caddy_config:
  blossom_cache:
